let car = 'sabru';
console.log("is car == 'sabru' ? I pridict true.");
console.log(car == 'sabru');
// now creating 10 tests
let fruit = "sweet";
console.log("is fruit == 'sweet' ? I pridict true.");
console.log(fruit == "sweet");
console.log("is fruit == 'sure' ? I pridict false.");
console.log(car == 'sure');
let mobile = "samsung";
console.log("is mobile == 'samsung' ? I pridict true.");
console.log(mobile == "samsung");
console.log("is mobile == 'iphone' ? I pridict false.");
console.log(car == 'iphone');
let country = "Pakistan";
console.log("is country == 'Pakistan' ? I pridict true.");
console.log(country == "Pakistan");
console.log("is country == 'japan' ? I pridict false.");
console.log(country == "japan");
let season = "winter";
console.log("is season == 'winter' ? I pridict true.");
console.log(season == "winter");
console.log("is season == 'summer' ? I pridict false.");
console.log(car == 'summer');
let laptop = "dell";
console.log("is laptop == 'dell' ? I pridict true.");
console.log(laptop == "dell");
console.log("is laptop == 'lenovo' ? I pridict false.");
console.log(laptop == 'lenovo');
export {};
